name: Build and Release EXE

on:
  push:
    branches:
      - gui-development

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build EXE using PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --onefile --windowed --icon=icon.ico --add-data "icon.ico;." app.py
          ren dist\app.exe Visualizer-v${{ github.run_number }}.exe

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: built-exe
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download built EXE
        uses: actions/download-artifact@v4
        with:
          name: built-exe
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: release-${{ github.run_number }}
          name: "Automated Release #${{ github.run_number }}"
          body: "This is an automated release for commit ${{ github.sha }}."
          draft: false
          prerelease: false
          files: dist/Visualizer-v${{ github.run_number }}.exe
